const cityArrWithAllCity = [
  {
    id: 1,
    name: "Agartala",
    value: "Agartala",
    state: "Tripura",
    status: false,
  },
  {
    id: 2,
    name: "Agra",
    value: "Agra",
    state: "Uttar Pradesh",
    status: false,
  },
  {
    id: 3,
    name: "Ahmedabad",
    value: "Ahmedabad",
    state: "Gujarat",
    status: false,
  },
  {
    id: 4,
    name: "Aizwal",
    value: "Aizwal",
    state: "Mizoram",
    status: false,
  },
  {
    id: 5,
    name: "Ajmer",
    value: "Ajmer",
    state: "Rajasthan",
    status: false,
  },
  {
    id: 6,
    name: "Allahabad",
    value: "Allahabad",
    state: "Uttar Pradesh",
    status: false,
  },
  {
    id: 7,
    name: "Alleppey",
    value: "Alleppey",
    state: "Kerala",
    status: false,
  },
  {
    id: 8,
    name: "Alibaug",
    value: "Alibaug",
    state: "Maharashtra",
    status: false,
  },
  {
    id: 9,
    name: "Almora",
    value: "Almora",
    state: "Uttaranchal",
    status: false,
  },
  {
    id: 10,
    name: "Alsisar",
    value: "Alsisar",
    state: "Rajasthan",
    status: false,
  },
  {
    id: 11,
    name: "Alwar",
    value: "Alwar",
    state: "Rajasthan",
    status: false,
  },
  {
    id: 12,
    name: "Ambala",
    value: "Ambala",
    state: "Haryana",
    status: false,
  },
  {
    id: 13,
    name: "Amla",
    value: "Amla",
    state: "Madhya Pradesh",
    status: false,
  },
  {
    id: 14,
    name: "Amritsar",
    value: "Amritsar",
    state: "Punjab",
    status: false,
  },
  {
    id: 15,
    name: "Anand",
    value: "Anand",
    state: "Gujarat",
    status: false,
  },
  {
    id: 16,
    name: "Ankleshwar",
    value: "Ankleshwar",
    state: "Gujarat",
    status: false,
  },
  {
    id: 17,
    name: "Ashtamudi",
    value: "Ashtamudi",
    state: "Kerala",
    status: false,
  },
  {
    id: 18,
    name: "Auli",
    value: "Auli",
    state: "Himachal Pradesh",
    status: false,
  },
  {
    id: 19,
    name: "Aurangabad",
    value: "Aurangabad",
    state: "Maharashtra",
    status: false,
  },
  {
    id: 20,
    name: "Baddi",
    value: "Baddi",
    state: "Himachal Pradesh",
    status: false,
  },
  {
    id: 21,
    name: "Badrinath",
    value: "Badrinath",
    state: "Uttaranchal",
    status: false,
  },
  {
    id: 22,
    name: "Balasinor",
    value: "Balasinor",
    state: "Gujarat",
    status: false,
  },
  {
    id: 23,
    name: "Balrampur",
    value: "Balrampur",
    state: "Uttar Pradesh",
    status: false,
  },
  {
    id: 24,
    name: "Bambora",
    value: "Bambora",
    state: "Rajasthan",
    status: false,
  },
  {
    id: 25,
    name: "Bandhavgarh",
    value: "Bandhavgarh",
    state: "Madhya Pradesh",
    status: false,
  },
  {
    id: 26,
    name: "Bandipur",
    value: "Bandipur",
    state: "Karnataka",
    status: false,
  },
  {
    id: 27,
    name: "Bangalore",
    value: "Bangalore",
    state: "Karnataka",
    status: false,
  },
  {
    id: 28,
    name: "Barbil",
    value: "Barbil",
    state: "Orissa",
    status: false,
  },
  {
    id: 29,
    name: "Bareilly",
    value: "Bareilly",
    state: "Uttar Pradesh",
    status: false,
  },
  {
    id: 30,
    name: "Behror",
    value: "Behror",
    state: "Rajasthan",
    status: false,
  },
  {
    id: 31,
    name: "Belgaum",
    value: "Belgaum",
    state: "Karnataka",
    status: false,
  },
  {
    id: 32,
    name: "Berhampur",
    value: "Berhampur",
    state: "Orissa",
    status: false,
  },
  {
    id: 33,
    name: "Betalghat",
    value: "Betalghat",
    state: "Uttaranchal",
    status: false,
  },
  {
    id: 34,
    name: "Bharatpur",
    value: "Bharatpur",
    state: "Rajasthan",
    status: false,
  },
  {
    id: 35,
    name: "Bhandardara",
    value: "Bhandardara",
    state: "Maharashtra",
    status: false,
  },
  {
    id: 36,
    name: "Bharuch",
    value: "Bharuch",
    state: "Gujarat",
    status: false,
  },
  {
    id: 37,
    name: "Bhavangadh",
    value: "Bhavangadh",
    state: "Gujarat",
    status: false,
  },
  {
    id: 38,
    name: "Bhavnagar",
    value: "Bhavnagar",
    state: "Gujarat",
    status: false,
  },
  {
    id: 39,
    name: "Bhilai",
    value: "Bhilai",
    state: "Chhattisgarh",
    status: false,
  },
  {
    id: 40,
    name: "Bhimtal",
    value: "Bhimtal",
    state: "Uttaranchal",
    status: false,
  },
  {
    id: 41,
    name: "Bhopal",
    value: "Bhopal",
    state: "Madhya Pradesh",
    status: false,
  },
  {
    id: 42,
    name: "Bhubaneshwar",
    value: "Bhubaneshwar",
    state: "Orissa",
    status: false,
  },
  {
    id: 43,
    name: "Bhuj",
    value: "Bhuj",
    state: "Gujarat",
    status: false,
  },
  {
    id: 44,
    name: "Bikaner",
    value: "Bikaner",
    state: "Rajasthan",
    status: false,
  },
  {
    id: 45,
    name: "Binsar",
    value: "Binsar",
    state: "Uttaranchal",
    status: false,
  },
  {
    id: 46,
    name: "Bodhgaya",
    value: "Bodhgaya",
    state: "Bihar",
    status: false,
  },
  {
    id: 47,
    name: "Bundi",
    value: "Bundi",
    state: "Rajasthan",
    status: false,
  },
  {
    id: 48,
    name: "Calicut",
    value: "Calicut",
    state: "Kerala",
    status: false,
  },
  {
    id: 49,
    name: "Canannore",
    value: "Canannore",
    state: "Kerala",
    status: false,
  },
  {
    id: 50,
    name: "Chail",
    value: "Chail",
    state: "Himachal Pradesh",
    status: false,
  },
  {
    id: 51,
    name: "Chamba",
    value: "Chamba",
    state: "Uttaranchal",
    status: false,
  },
  {
    id: 52,
    name: "Chandigarh",
    value: "Chandigarh",
    state: "Punjab",
    status: false,
  },
  {
    id: 53,
    name: "Chennai",
    value: "Chennai",
    state: "Tamil Nadu",
    status: false,
  },
  {
    id: 54,
    name: "Chikmagalur",
    value: "Chikmagalur",
    state: "Karnataka",
    status: false,
  },
  {
    id: 55,
    name: "Chiplun",
    value: "Chiplun",
    state: "Maharashtra",
    status: false,
  },
  {
    id: 56,
    name: "Chitrakoot",
    value: "Chitrakoot",
    state: "Madhya Pradesh",
    status: false,
  },
  {
    id: 57,
    name: "Chittorgarh",
    value: "Chittorgarh",
    state: "Rajasthan",
    status: false,
  },
  {
    id: 58,
    name: "Coimbatore",
    value: "Coimbatore",
    state: "Tamil Nadu",
    status: false,
  },
  {
    id: 59,
    name: "Coonoor",
    value: "Coonoor",
    state: "Tamil Nadu",
    status: false,
  },
  {
    id: 60,
    name: "Coorg",
    value: "Coorg",
    state: "Karnataka",
    status: false,
  },
  {
    id: 61,
    name: "Corbett National Park",
    value: "Corbett National Park",
    state: "Uttaranchal",
    status: false,
  },
  {
    id: 62,
    name: "Cuttack",
    value: "Cuttack",
    state: "Orissa",
    status: false,
  },
  {
    id: 63,
    name: "Dabhosa",
    value: "Dabhosa",
    state: "Maharashtra",
    status: false,
  },
  {
    id: 64,
    name: "Dalhousie",
    value: "Dalhousie",
    state: "Himachal Pradesh",
    status: false,
  },
  {
    id: 65,
    name: "Daman",
    value: "Daman",
    state: "Union Territory Of Dadra & Nagar Haveli",
    status: false,
  },
  {
    id: 66,
    name: "Dandeli",
    value: "Dandeli",
    state: "Karnataka",
    status: false,
  },
  {
    id: 67,
    name: "Dapoli",
    value: "Dapoli",
    state: "Maharashtra",
    status: false,
  },
  {
    id: 68,
    name: "Darjeeling",
    value: "Darjeeling",
    state: "West Bengal",
    status: false,
  },
  {
    id: 69,
    name: "Dausa",
    value: "Dausa",
    state: "Rajasthan",
    status: false,
  },
  {
    id: 70,
    name: "Dehradun",
    value: "Dehradun",
    state: "Uttar Pradesh",
    status: false,
  },
  {
    id: 71,
    name: "Dharamshala",
    value: "Dharamshala",
    state: "Himachal Pradesh",
    status: false,
  },
  {
    id: 72,
    name: "Dibrugarh",
    value: "Dibrugarh",
    state: "Assam",
    status: false,
  },
  {
    id: 73,
    name: "Digha",
    value: "Digha",
    state: "West Bengal",
    status: false,
  },
  {
    id: 74,
    name: "Diu",
    value: "Diu",
    state: "Union Territory Of Dadra & Nagar Haveli",
    status: false,
  },
  {
    id: 75,
    name: "Dive Agar",
    value: "Dive Agar",
    state: "Maharashtra",
    status: false,
  },
  {
    id: 76,
    name: "Dooars",
    value: "Dooars",
    state: "West Bengal",
    status: false,
  },
  {
    id: 77,
    name: "Durgapur",
    value: "Durgapur",
    state: "West Bengal",
    status: false,
  },
  {
    id: 78,
    name: "Durshet",
    value: "Durshet",
    state: "Maharashtra",
    status: false,
  },
  {
    id: 79,
    name: "Dwarka",
    value: "Dwarka",
    state: "Gujarat",
    status: false,
  },
  {
    id: 80,
    name: "Faridabad",
    value: "Faridabad",
    state: "Haryana",
    status: false,
  },
  {
    id: 81,
    name: "Firozabad",
    value: "Firozabad",
    state: "Uttar Pradesh",
    status: false,
  },
  {
    id: 82,
    name: "Gangotri",
    value: "Gangotri",
    state: "Uttaranchal",
    status: false,
  },
  {
    id: 83,
    name: "Gangtok",
    value: "Gangtok",
    state: "Sikkim",
    status: false,
  },
  {
    id: 84,
    name: "Ganapatipule",
    value: "Ganapatipule",
    state: "Maharashtra",
    status: false,
  },
  {
    id: 85,
    name: "Gandhidham",
    value: "Gandhidham",
    state: "Gujarat",
    status: false,
  },
  {
    id: 86,
    name: "Gandhinagar",
    value: "Gandhinagar",
    state: "Gujarat",
    status: false,
  },
  {
    id: 87,
    name: "Garhmukteshwar",
    value: "Garhmukteshwar",
    state: "Uttar Pradesh",
    status: false,
  },
  {
    id: 88,
    name: "Garhwal",
    value: "Garhwal",
    state: "Uttaranchal",
    status: false,
  },
  {
    id: 89,
    name: "Gaya",
    value: "Gaya",
    state: "Bihar",
    status: false,
  },
  {
    id: 90,
    name: "Ghaziabad",
    value: "Ghaziabad",
    state: "New Delhi",
    status: false,
  },
  {
    id: 91,
    name: "Goa",
    value: "Goa",
    state: "Goa",
    status: false,
  },
  {
    id: 92,
    name: "Gokharna",
    value: "Gokharna",
    state: "Kerala",
    status: false,
  },
  {
    id: 93,
    name: "Gondal",
    value: "Gondal",
    state: "Gujarat",
    status: false,
  },
  {
    id: 94,
    name: "Gorakhpur",
    value: "Gorakhpur",
    state: "Uttar Pradesh",
    status: false,
  },
  {
    id: 95,
    name: "Greater Noida",
    value: "Greater Noida",
    state: "Ncr",
    status: false,
  },
  {
    id: 96,
    name: "Gulmarg",
    value: "Gulmarg",
    state: "Jammu & Kashmir",
    status: false,
  },
  {
    id: 97,
    name: "Gurgaon",
    value: "Gurgaon",
    state: "Haryana",
    status: false,
  },
  {
    id: 98,
    name: "Guruvayoor",
    value: "Guruvayoor",
    state: "Kerala",
    status: false,
  },
  {
    id: 99,
    name: "Guwahati",
    value: "Guwahati",
    state: "Assam",
    status: false,
  },
  {
    id: 100,
    name: "Gwalior",
    value: "Gwalior",
    state: "Madhya Pradesh",
    status: false,
  },
  {
    id: 101,
    name: "Halebid",
    value: "Halebid",
    state: "Karnataka",
    status: false,
  },
  {
    id: 102,
    name: "Hampi",
    value: "Hampi",
    state: "Karnataka",
    status: false,
  },
  {
    id: 103,
    name: "Hansi",
    value: "Hansi",
    state: "Haryana",
    status: false,
  },
  {
    id: 104,
    name: "Haridwar",
    value: "Haridwar",
    state: "Uttar Pradesh",
    status: false,
  },
  {
    id: 105,
    name: "Hassan",
    value: "Hassan",
    state: "Karnataka",
    status: false,
  },
  {
    id: 106,
    name: "Hospet",
    value: "Hospet",
    state: "Karnataka",
    status: false,
  },
  {
    id: 107,
    name: "Hosur",
    value: "Hosur",
    state: "Tamil Nadu",
    status: false,
  },
  {
    id: 108,
    name: "Hubli",
    value: "Hubli",
    state: "Karnataka",
    status: false,
  },
  {
    id: 109,
    name: "Hyderabad",
    value: "Hyderabad",
    state: "Andhra Pradesh",
    status: false,
  },
  {
    id: 110,
    name: "Idukki",
    value: "Idukki",
    state: "Kerala",
    status: false,
  },
  {
    id: 111,
    name: "Igatpuri",
    value: "Igatpuri",
    state: "Maharashtra",
    status: false,
  },
  {
    id: 112,
    name: "Imphal",
    value: "Imphal",
    state: "Manipur",
    status: false,
  },
  {
    id: 113,
    name: "Indore",
    value: "Indore",
    state: "Madhya Pradesh",
    status: false,
  },
  {
    id: 114,
    name: "Jabalpur",
    value: "Jabalpur",
    state: "Madhya Pradesh",
    status: false,
  },
  {
    id: 115,
    name: "Jaipur",
    value: "Jaipur",
    state: "Rajasthan",
    status: false,
  },
  {
    id: 116,
    name: "Jaisalmer",
    value: "Jaisalmer",
    state: "Rajasthan",
    status: false,
  },
  {
    id: 117,
    name: "Jalandhar",
    value: "Jalandhar",
    state: "Punjab",
    status: false,
  },
  {
    id: 118,
    name: "Jalgaon",
    value: "Jalgaon",
    state: "Maharashtra",
    status: false,
  },
  {
    id: 119,
    name: "Jambugodha",
    value: "Jambugodha",
    state: "Gujarat",
    status: false,
  },
  {
    id: 120,
    name: "Jammu",
    value: "Jammu",
    state: "Jammu & Kashmir",
    status: false,
  },
  {
    id: 121,
    name: "Jamnagar",
    value: "Jamnagar",
    state: "Gujarat",
    status: false,
  },
  {
    id: 122,
    name: "Jamshedpur",
    value: "Jamshedpur",
    state: "Jharkhand",
    status: false,
  },
  {
    id: 123,
    name: "Jawhar",
    value: "Jawhar",
    state: "Maharashtra",
    status: false,
  },
  {
    id: 124,
    name: "Jhansi",
    value: "Jhansi",
    state: "Uttar Pradesh",
    status: false,
  },
  {
    id: 125,
    name: "Jodhpur",
    value: "Jodhpur",
    state: "Rajasthan",
    status: false,
  },
  {
    id: 126,
    name: "Jojawar",
    value: "Jojawar",
    state: "Rajasthan",
    status: false,
  },
  {
    id: 127,
    name: "Jorhat",
    value: "Jorhat",
    state: "Assam",
    status: false,
  },
  {
    id: 128,
    name: "Junagadh",
    value: "Junagadh",
    state: "Gujarat",
    status: false,
  },
  {
    id: 129,
    name: "Kabini",
    value: "Kabini",
    state: "Karnataka",
    status: false,
  },
  {
    id: 130,
    name: "Kalimpong",
    value: "Kalimpong",
    state: "West Bengal",
    status: false,
  },
  {
    id: 131,
    name: "Kanatal",
    value: "Kanatal",
    state: "Uttaranchal",
    status: false,
  },
  {
    id: 132,
    name: "Kanchipuram",
    value: "Kanchipuram",
    state: "Tamil Nadu",
    status: false,
  },
  {
    id: 133,
    name: "Kanha",
    value: "Kanha",
    state: "Madhya Pradesh",
    status: false,
  },
  {
    id: 134,
    name: "Kanpur",
    value: "Kanpur",
    state: "Uttar Pradesh",
    status: false,
  },
  {
    id: 135,
    name: "Kanyakumari",
    value: "Kanyakumari",
    state: "Tamil Nadu",
    status: false,
  },
  {
    id: 136,
    name: "Kargil",
    value: "Kargil",
    state: "Jammu & Kashmir",
    status: false,
  },
  {
    id: 137,
    name: "Karjat",
    value: "Karjat",
    state: "Maharashtra",
    status: false,
  },
  {
    id: 138,
    name: "Karnal",
    value: "Karnal",
    state: "Haryana",
    status: false,
  },
  {
    id: 139,
    name: "Karur",
    value: "Karur",
    state: "Tamil Nadu",
    status: false,
  },
  {
    id: 140,
    name: "Karwar",
    value: "Karwar",
    state: "Karnataka",
    status: false,
  },
  {
    id: 141,
    name: "Kasargod",
    value: "Kasargod",
    state: "Kerala",
    status: false,
  },
  {
    id: 142,
    name: "Kasauli",
    value: "Kasauli",
    state: "Himachal Pradesh",
    status: false,
  },
  {
    id: 143,
    name: "Kashipur",
    value: "Kashipur",
    state: "Uttaranchal",
    status: false,
  },
  {
    id: 144,
    name: "Kashid",
    value: "Kashid",
    state: "Maharashtra",
    status: false,
  },
  {
    id: 145,
    name: "Katra",
    value: "Katra",
    state: "Jammu & Kashmir",
    status: false,
  },
  {
    id: 146,
    name: "Kausani",
    value: "Kausani",
    state: "Uttarakhand",
    status: false,
  },
  {
    id: 147,
    name: "Kaza",
    value: "Kaza",
    state: "Himachal Pradesh",
    status: false,
  },
  {
    id: 148,
    name: "Kaziranga",
    value: "Kaziranga",
    state: "Assam",
    status: false,
  },
  {
    id: 149,
    name: "Kedarnath",
    value: "Kedarnath",
    state: "Uttaranchal",
    status: false,
  },
  {
    id: 150,
    name: "Khajjiar",
    value: "Khajjiar",
    state: "Himachal Pradesh",
    status: false,
  },
  {
    id: 151,
    name: "Khajuraho",
    value: "Khajuraho",
    state: "Madhya Pradesh",
    status: false,
  },
  {
    id: 152,
    name: "Khandala",
    value: "Khandala",
    state: "Maharashtra",
    status: false,
  },
  {
    id: 153,
    name: "Khimsar",
    value: "Khimsar",
    state: "Rajasthan",
    status: false,
  },
  {
    id: 154,
    name: "Kochin",
    value: "Kochin",
    state: "Kerala",
    status: false,
  },
  {
    id: 155,
    name: "Kodaikanal",
    value: "Kodaikanal",
    state: "Tamil Nadu",
    status: false,
  },
  {
    id: 156,
    name: "Kolhapur",
    value: "Kolhapur",
    state: "Maharashtra",
    status: false,
  },
  {
    id: 157,
    name: "Kolkata",
    value: "Kolkata",
    state: "West Bengal",
    status: false,
  },
  {
    id: 158,
    name: "Kollam",
    value: "Kollam",
    state: "Kerala",
    status: false,
  },
  {
    id: 159,
    name: "Kota",
    value: "Kota",
    state: "Rajasthan",
    status: false,
  },
  {
    id: 160,
    name: "Kotagiri",
    value: "Kotagiri",
    state: "Tamil Nadu",
    status: false,
  },
  {
    id: 161,
    name: "Kottayam",
    value: "Kottayam",
    state: "Kerala",
    status: false,
  },
  {
    id: 162,
    name: "Kovalam",
    value: "Kovalam",
    state: "Kerala",
    status: false,
  },
  {
    id: 163,
    name: "Kufri",
    value: "Kufri",
    state: "Himachal Pradesh",
    status: false,
  },
  {
    id: 164,
    name: "Kumbalgarh",
    value: "Kumbalgarh",
    state: "Rajasthan",
    status: false,
  },
  {
    id: 165,
    name: "Kullu",
    value: "Kullu",
    state: "Himachal Pradesh",
    status: false,
  },
  {
    id: 166,
    name: "Kumarakom",
    value: "Kumarakom",
    state: "Kerala",
    status: false,
  },
  {
    id: 167,
    name: "Kumbakonam",
    value: "Kumbakonam",
    state: "Tamil Nadu",
    status: false,
  },
  {
    id: 168,
    name: "Kumily",
    value: "Kumily",
    state: "Kerala",
    status: false,
  },
  {
    id: 169,
    name: "Kurseong",
    value: "Kurseong",
    state: "West Bengal",
    status: false,
  },
  {
    id: 170,
    name: "Kushinagar",
    value: "Kushinagar",
    state: "Uttar Pradesh",
    status: false,
  },
  {
    id: 171,
    name: "Lachung",
    value: "Lachung",
    state: "North Sikkim",
    status: false,
  },
  {
    id: 172,
    name: "Leh",
    value: "Leh",
    state: "Jammu &amp; Kashmir",
    status: false,
  },
  {
    id: 173,
    name: "Lakshadweep",
    value: "Lakshadweep",
    state: "Union Territory Of Lakshadweep",
    status: false,
  },
  {
    id: 174,
    name: "Lonavala",
    value: "Lonavala",
    state: "Maharashtra",
    status: false,
  },
  {
    id: 175,
    name: "Lothal",
    value: "Lothal",
    state: "Gujarat",
    status: false,
  },
  {
    id: 176,
    name: "Lucknow",
    value: "Lucknow",
    state: "Uttar Pradesh",
    status: false,
  },
  {
    id: 177,
    name: "Ludhiana",
    value: "Ludhiana",
    state: "Punjab",
    status: false,
  },
  {
    id: 178,
    name: "Lumbini",
    value: "Lumbini",
    state: "Nepal",
    status: false,
  },
  {
    id: 179,
    name: "Madurai",
    value: "Madurai",
    state: "Tamil Nadu",
    status: false,
  },
  {
    id: 180,
    name: "Mahabaleshwar",
    value: "Mahabaleshwar",
    state: "Maharashtra",
    status: false,
  },
  {
    id: 181,
    name: "Mahabalipuram",
    value: "Mahabalipuram",
    state: "Tamil Nadu",
    status: false,
  },
  {
    id: 182,
    name: "Malappuram",
    value: "Malappuram",
    state: "Kerala",
    status: false,
  },
  {
    id: 183,
    name: "Malpe",
    value: "Malpe",
    state: "Karnataka",
    status: false,
  },
  {
    id: 184,
    name: "Malshej Ghat",
    value: "Malshej Ghat",
    state: "Maharashtra",
    status: false,
  },
  {
    id: 185,
    name: "Malvan",
    value: "Malvan",
    state: "Maharashtra",
    status: false,
  },
  {
    id: 186,
    name: "Manali",
    value: "Manali",
    state: "Himachal Pradesh",
    status: false,
  },
  {
    id: 187,
    name: "Mandavi",
    value: "Mandavi",
    state: "Gujarat",
    status: false,
  },
  {
    id: 188,
    name: "Mandawa",
    value: "Mandawa",
    state: "Rajasthan",
    status: false,
  },
  {
    id: 189,
    name: "Manesar",
    value: "Manesar",
    state: "Haryana",
    status: false,
  },
  {
    id: 190,
    name: "Mararri",
    value: "Mararri",
    state: "Kerala",
    status: false,
  },
  {
    id: 191,
    name: "Mandormoni",
    value: "Mandormoni",
    state: "West Bengal",
    status: false,
  },
  {
    id: 192,
    name: "Mangalore",
    value: "Mangalore",
    state: "Karnataka",
    status: false,
  },
  {
    id: 193,
    name: "Manmad",
    value: "Manmad",
    state: "Maharashtra",
    status: false,
  },
  {
    id: 194,
    name: "Marchula",
    value: "Marchula",
    state: "Uttaranchal",
    status: false,
  },
  {
    id: 195,
    name: "Matheran",
    value: "Matheran",
    state: "Maharashtra",
    status: false,
  },
  {
    id: 196,
    name: "Mathura",
    value: "Mathura",
    state: "Uttar Pradesh",
    status: false,
  },
  {
    id: 197,
    name: "Mcleodganj",
    value: "Mcleodganj",
    state: "Himachal Pradesh",
    status: false,
  },
  {
    id: 198,
    name: "Mohali",
    value: "Mohali",
    state: "Punjab",
    status: false,
  },
  {
    id: 199,
    name: "Mount Abu",
    value: "Mount Abu",
    state: "Rajasthan",
    status: false,
  },
  {
    id: 200,
    name: "Moradabad",
    value: "Moradabad",
    state: "Uttar Pradesh",
    status: false,
  },
  {
    id: 201,
    name: "Morbi",
    value: "Morbi",
    state: "Gujarat",
    status: false,
  },
  {
    id: 202,
    name: "Mukteshwar",
    value: "Mukteshwar",
    state: "Uttaranchal",
    status: false,
  },
  {
    id: 203,
    name: "Mumbai",
    value: "Mumbai",
    state: "Maharashtra",
    status: false,
  },
  {
    id: 204,
    name: "Mundra",
    value: "Mundra",
    state: "Maharashtra",
    status: false,
  },
  {
    id: 205,
    name: "Munnar",
    value: "Munnar",
    state: "Kerala",
    status: false,
  },
  {
    id: 206,
    name: "Murud Janjira",
    value: "Murud Janjira",
    state: "Maharashtra",
    status: false,
  },
  {
    id: 207,
    name: "Mussoorie",
    value: "Mussoorie",
    state: "Uttaranchal",
    status: false,
  },
  {
    id: 208,
    name: "Mysore",
    value: "Mysore",
    state: "Karnataka",
    status: false,
  },
  {
    id: 209,
    name: "Nadukani",
    value: "Nadukani",
    state: "Kerala",
    status: false,
  },
  {
    id: 210,
    name: "Nagapattinam",
    value: "Nagapattinam",
    state: "Tamil Nadu",
    status: false,
  },
  {
    id: 211,
    name: "Nagarhole",
    value: "Nagarhole",
    state: "Karnataka",
    status: false,
  },
  {
    id: 212,
    name: "Nagaur Fort",
    value: "Nagaur Fort",
    state: "Rajasthan",
    status: false,
  },
  {
    id: 213,
    name: "Nagothane",
    value: "Nagothane",
    state: "Maharashtra",
    status: false,
  },
  {
    id: 214,
    name: "Nagpur",
    value: "Nagpur",
    state: "Maharashtra",
    status: false,
  },
  {
    id: 215,
    name: "Nahan",
    value: "Nahan",
    state: "Himachal Pradesh",
    status: false,
  },
  {
    id: 216,
    name: "Nainital",
    value: "Nainital",
    state: "Uttar Pradesh",
    status: false,
  },
  {
    id: 217,
    name: "Naldhera",
    value: "Naldhera",
    state: "Himachal Pradesh",
    status: false,
  },
  {
    id: 218,
    name: "Nanded",
    value: "Nanded",
    state: "Maharashtra",
    status: false,
  },
  {
    id: 219,
    name: "Napne",
    value: "Napne",
    state: "Maharashtra",
    status: false,
  },
  {
    id: 220,
    name: "Nasik",
    value: "Nasik",
    state: "Maharashtra",
    status: false,
  },
  {
    id: 221,
    name: "Navi Mumbai",
    value: "Navi Mumbai",
    state: "Maharashtra",
    status: false,
  },
  {
    id: 222,
    name: "Neral",
    value: "Neral",
    state: "Maharashtra",
    status: false,
  },
  {
    id: 223,
    name: "Delhi",
    value: "Delhi",
    state: "Delhi",
    status: false,
  },
  {
    id: 224,
    name: "Nilgiri",
    value: "Nilgiri",
    state: "Tamil Nadu",
    status: false,
  },
  {
    id: 225,
    name: "Noida",
    value: "Noida",
    state: "Uttar Pradesh",
    status: false,
  },
  {
    id: 226,
    name: "Ooty",
    value: "Ooty",
    state: "Tamil Nadu",
    status: false,
  },
  {
    id: 227,
    name: "Orchha",
    value: "Orchha",
    state: "Madhya Pradesh",
    status: false,
  },
  {
    id: 228,
    name: "Osian",
    value: "Osian",
    state: "Rajasthan",
    status: false,
  },
  {
    id: 229,
    name: "Pachmarhi",
    value: "Pachmarhi",
    state: "Madhya Pradesh",
    status: false,
  },
  {
    id: 230,
    name: "Palampur",
    value: "Palampur",
    state: "Himachal Pradesh",
    status: false,
  },
  {
    id: 231,
    name: "Palanpur",
    value: "Palanpur",
    state: "Gujarat",
    status: false,
  },
  {
    id: 232,
    name: "Pali",
    value: "Pali",
    state: "Rajasthan",
    status: false,
  },
  {
    id: 233,
    name: "Pahalgam",
    value: "Pahalgam",
    state: "Jammu & Kashmir",
    status: false,
  },
  {
    id: 234,
    name: "Palitana",
    value: "Palitana",
    state: "Gujarat",
    status: false,
  },
  {
    id: 235,
    name: "Pallakad",
    value: "Pallakad",
    state: "Kerala",
    status: false,
  },
  {
    id: 236,
    name: "Panchgani",
    value: "Panchgani",
    state: "Maharashtra",
    status: false,
  },
  {
    id: 237,
    name: "Panchkula",
    value: "Panchkula",
    state: "Haryana",
    status: false,
  },
  {
    id: 238,
    name: "Panna",
    value: "Panna",
    state: "Madhya Pradesh",
    status: false,
  },
  {
    id: 239,
    name: "Panhala",
    value: "Panhala",
    state: "Maharashtra",
    status: false,
  },
  {
    id: 240,
    name: "Panvel",
    value: "Panvel",
    state: "Maharashtra",
    status: false,
  },
  {
    id: 241,
    name: "Pantnagar",
    value: "Pantnagar",
    state: "Uttaranchal",
    status: false,
  },
  {
    id: 242,
    name: "Parwanoo",
    value: "Parwanoo",
    state: "Himachal Pradesh",
    status: false,
  },
  {
    id: 243,
    name: "Patiala",
    value: "Patiala",
    state: "Punjab",
    status: false,
  },
  {
    id: 244,
    name: "Pathankot",
    value: "Pathankot",
    state: "Jammu & Kashmir",
    status: false,
  },
  {
    id: 245,
    name: "Patna",
    value: "Patna",
    state: "Bihar",
    status: false,
  },
  {
    id: 246,
    name: "Patnitop",
    value: "Patnitop",
    state: "Jammu & Kashmir",
    status: false,
  },
  {
    id: 247,
    name: "Pelling",
    value: "Pelling",
    state: "West Sikkim",
    status: false,
  },
  {
    id: 248,
    name: "Pench",
    value: "Pench",
    state: "Madhya Pradesh",
    status: false,
  },
  {
    id: 249,
    name: "Phagwara",
    value: "Phagwara",
    state: "Punjab",
    status: false,
  },
  {
    id: 250,
    name: "Phalodi",
    value: "Phalodi",
    state: "Rajasthan",
    status: false,
  },
  {
    id: 251,
    name: "Pinjore",
    value: "Pinjore",
    state: "Haryana",
    status: false,
  },
  {
    id: 252,
    name: "Pondicherry",
    value: "Pondicherry",
    state: "Tamil Nadu",
    status: false,
  },
  {
    id: 253,
    name: "Poovar",
    value: "Poovar",
    state: "Kerala",
    status: false,
  },
  {
    id: 254,
    name: "Porbandar",
    value: "Porbandar",
    state: "Gujarat",
    status: false,
  },
  {
    id: 255,
    name: "Port Blair",
    value: "Port Blair",
    state: "Andaman &amp; Nicobar Islands",
    status: false,
  },
  {
    id: 256,
    name: "Poshina",
    value: "Poshina",
    state: "Gujarat",
    status: false,
  },
  {
    id: 257,
    name: "Pragpur",
    value: "Pragpur",
    state: "Himachal Pradesh",
    status: false,
  },
  {
    id: 258,
    name: "Pune",
    value: "Pune",
    state: "Maharashtra",
    status: false,
  },
  {
    id: 259,
    name: "Puri",
    value: "Puri",
    state: "Orissa",
    status: false,
  },
  {
    id: 260,
    name: "Puskhar",
    value: "Puskhar",
    state: "Rajasthan",
    status: false,
  },
  {
    id: 261,
    name: "Puttaparthi",
    value: "Puttaparthi",
    state: "Andhra Pradesh",
    status: false,
  },
  {
    id: 262,
    name: "Rai Bareilly",
    value: "Rai Bareilly",
    state: "Uttar Pradesh",
    status: false,
  },
  {
    id: 263,
    name: "Raichak",
    value: "Raichak",
    state: "West Bengal",
    status: false,
  },
  {
    id: 264,
    name: "Raipur",
    value: "Raipur",
    state: "Chhattisgarh",
    status: false,
  },
  {
    id: 265,
    name: "Rajasthan",
    value: "Rajasthan",
    state: "Rajasthan",
    status: false,
  },
  {
    id: 266,
    name: "Rajgir",
    value: "Rajgir",
    state: "Bihar",
    status: false,
  },
  {
    id: 267,
    name: "Rajkot",
    value: "Rajkot",
    state: "Gujarat",
    status: false,
  },
  {
    id: 268,
    name: "Rajpipla",
    value: "Rajpipla",
    state: "Gujarat",
    status: false,
  },
  {
    id: 269,
    name: "Rajsamand",
    value: "Rajsamand",
    state: "Rajasthan",
    status: false,
  },
  {
    id: 270,
    name: "Rajahmundry",
    value: "Rajahmundry",
    state: "Andhra Pradesh",
    status: false,
  },
  {
    id: 271,
    name: "Rameshwaram",
    value: "Rameshwaram",
    state: "Tamil Nadu",
    status: false,
  },
  {
    id: 272,
    name: "Ram Nagar",
    value: "Ram Nagar",
    state: "Uttar Pradesh",
    status: false,
  },
  {
    id: 273,
    name: "Ramgarh",
    value: "Ramgarh",
    state: "Rajasthan",
    status: false,
  },
  {
    id: 274,
    name: "Ranakpur",
    value: "Ranakpur",
    state: "Rajasthan",
    status: false,
  },
  {
    id: 275,
    name: "Ranchi",
    value: "Ranchi",
    state: "Jharkhand",
    status: false,
  },
  {
    id: 276,
    name: "Ranikhet",
    value: "Ranikhet",
    state: "Uttaranchal",
    status: false,
  },
  {
    id: 277,
    name: "Ranny",
    value: "Ranny",
    state: "Kerala",
    status: false,
  },
  {
    id: 278,
    name: "Ranthambore",
    value: "Ranthambore",
    state: "Rajasthan",
    status: false,
  },
  {
    id: 279,
    name: "Ratnagiri",
    value: "Ratnagiri",
    state: "Maharashtra",
    status: false,
  },
  {
    id: 280,
    name: "Ravangla",
    value: "Ravangla",
    state: "Sikkim",
    status: false,
  },
  {
    id: 281,
    name: "Rishikesh",
    value: "Rishikesh",
    state: "Uttar Pradesh",
    status: false,
  },
  {
    id: 282,
    name: "Rishyap",
    value: "Rishyap",
    state: "West Bengal",
    status: false,
  },
  {
    id: 283,
    name: "Rohetgarh",
    value: "Rohetgarh",
    state: "Rajasthan",
    status: false,
  },
  {
    id: 284,
    name: "Rourkela",
    value: "Rourkela",
    state: "Orissa",
    status: false,
  },
  {
    id: 285,
    name: "Sajan",
    value: "Sajan",
    state: "Maharashtra",
    status: false,
  },
  {
    id: 286,
    name: "Salem",
    value: "Salem",
    state: "Tamil Nadu",
    status: false,
  },
  {
    id: 287,
    name: "Saputara",
    value: "Saputara",
    state: "Gujarat",
    status: false,
  },
  {
    id: 288,
    name: "Sasan Gir",
    value: "Sasan Gir",
    state: "Gujarat",
    status: false,
  },
  {
    id: 289,
    name: "Sattal",
    value: "Sattal",
    state: "Uttaranchal",
    status: false,
  },
  {
    id: 290,
    name: "Sawai Madhopur",
    value: "Sawai Madhopur",
    state: "Rajasthan",
    status: false,
  },
  {
    id: 291,
    name: "Sawantwadi",
    value: "Sawantwadi",
    state: "Maharashtra",
    status: false,
  },
  {
    id: 292,
    name: "Secunderabad",
    value: "Secunderabad",
    state: "Andhra Pradesh",
    status: false,
  },
  {
    id: 293,
    name: "Shillong",
    value: "Shillong",
    state: "Meghalaya",
    status: false,
  },
  {
    id: 294,
    name: "Shimla",
    value: "Shimla",
    state: "Himachal Pradesh",
    status: false,
  },
  {
    id: 295,
    name: "Shimlipal",
    value: "Shimlipal",
    state: "Orissa",
    status: false,
  },
  {
    id: 296,
    name: "Shirdi",
    value: "Shirdi",
    state: "Maharashtra",
    status: false,
  },
  {
    id: 297,
    name: "Sharavanbelgola",
    value: "Sharavanbelgola",
    state: "Karnataka",
    status: false,
  },
  {
    id: 298,
    name: "Shivanasamudra",
    value: "Shivanasamudra",
    state: "Karnataka",
    status: false,
  },
  {
    id: 299,
    name: "Siana",
    value: "Siana",
    state: "Rajasthan",
    status: false,
  },
  {
    id: 300,
    name: "Siliguri",
    value: "Siliguri",
    state: "West Bengal",
    status: false,
  },
  {
    id: 301,
    name: "Silvassa",
    value: "Silvassa",
    state: "Union Territory Of Dadra & Nagar Haveli",
    status: false,
  },
  {
    id: 302,
    name: "Sivaganga District",
    value: "Sivaganga District",
    state: "Tamil Nadu",
    status: false,
  },
  {
    id: 303,
    name: "Solan",
    value: "Solan",
    state: "Himachal Pradesh",
    status: false,
  },
  {
    id: 304,
    name: "Sonauli",
    value: "Sonauli",
    state: "Uttar Pradesh",
    status: false,
  },
  {
    id: 305,
    name: "Srinagar",
    value: "Srinagar",
    state: "Jammu &amp; Kashmir",
    status: false,
  },
  {
    id: 306,
    name: "Sunderban",
    value: "Sunderban",
    state: "West Bengal",
    status: false,
  },
  {
    id: 307,
    name: "Surat",
    value: "Surat",
    state: "Gujarat",
    status: false,
  },
  {
    id: 308,
    name: "Tanjore",
    value: "Tanjore",
    state: "Tamil Nadu",
    status: false,
  },
  {
    id: 309,
    name: "Tapola",
    value: "Tapola",
    state: "Maharashtra",
    status: false,
  },
  {
    id: 310,
    name: "Tarapith",
    value: "Tarapith",
    state: "West Bengal",
    status: false,
  },
  {
    id: 311,
    name: "Thane",
    value: "Thane",
    state: "Maharashtra",
    status: false,
  },
  {
    id: 312,
    name: "Thekkady",
    value: "Thekkady",
    state: "Kerala",
    status: false,
  },
  {
    id: 313,
    name: "Thirvannamalai",
    value: "Thirvannamalai",
    state: "Tamil Nadu",
    status: false,
  },
  {
    id: 314,
    name: "Thiruvananthapuram",
    value: "Thiruvananthapuram",
    state: "Kerala",
    status: false,
  },
  {
    id: 315,
    name: "Tiruchirapalli",
    value: "Tiruchirapalli",
    state: "Tamil Nadu",
    status: false,
  },
  {
    id: 316,
    name: "Tirupur",
    value: "Tirupur",
    state: "Tamil Nadu",
    status: false,
  },
  {
    id: 317,
    name: "Tirupati",
    value: "Tirupati",
    state: "Andhra Pradesh",
    status: false,
  },
  {
    id: 318,
    name: "Thrissur",
    value: "Thrissur",
    state: "Kerala",
    status: false,
  },
  {
    id: 319,
    name: "Udaipur",
    value: "Udaipur",
    state: "Rajasthan",
    status: false,
  },
  {
    id: 320,
    name: "Udhampur",
    value: "Udhampur",
    state: "Jammu & Kashmir",
    status: false,
  },
  {
    id: 321,
    name: "Udupi",
    value: "Udupi",
    state: "Karnataka",
    status: false,
  },
  {
    id: 322,
    name: "Ujjain",
    value: "Ujjain",
    state: "Madhya Pradesh",
    status: false,
  },
  {
    id: 323,
    name: "Uttarkashi",
    value: "Uttarkashi",
    state: "Uttaranchal",
    status: false,
  },
  {
    id: 324,
    name: "Vadodara",
    value: "Vadodara",
    state: "Gujarat",
    status: false,
  },
  {
    id: 325,
    name: "Vagamon",
    value: "Vagamon",
    state: "Kerala",
    status: false,
  },
  {
    id: 326,
    name: "Varkala",
    value: "Varkala",
    state: "Kerala",
    status: false,
  },
  {
    id: 327,
    name: "Vapi",
    value: "Vapi",
    state: "Gujarat",
    status: false,
  },
  {
    id: 328,
    name: "Varanasi",
    value: "Varanasi",
    state: "Uttar Pradesh",
    status: false,
  },
  {
    id: 329,
    name: "Velankanni",
    value: "Velankanni",
    state: "Tamil Nadu",
    status: false,
  },
  {
    id: 330,
    name: "Vellore",
    value: "Vellore",
    state: "Tamil Nadu",
    status: false,
  },
  {
    id: 331,
    name: "Veraval",
    value: "Veraval",
    state: "Maharashtra",
    status: false,
  },
  {
    id: 332,
    name: "Vijayawada",
    value: "Vijayawada",
    state: "Andhra Pradesh",
    status: false,
  },
  {
    id: 333,
    name: "Vikramgadh",
    value: "Vikramgadh",
    state: "Maharashtra",
    status: false,
  },
  {
    id: 334,
    name: "Vishakapatnam",
    value: "Vishakapatnam",
    state: "Andhra Pradesh",
    status: false,
  },
  {
    id: 335,
    name: "Wayanad",
    value: "Wayanad",
    state: "Kerala",
    status: false,
  },
  {
    id: 336,
    name: "Wankaner",
    value: "Wankaner",
    state: "Gujarat",
    status: false,
  },
  {
    id: 337,
    name: "Yamunotri",
    value: "Yamunotri",
    state: "Uttaranchal",
    status: false,
  },
  {
    id: 338,
    name: "Yercaud",
    value: "Yercaud",
    state: "Tamil Nadu",
    status: false,
  },
  {
    id: 339,
    name: "Yuksom",
    value: "Yuksom",
    state: "Sikkim",
    status: false,
  },
];
module.exports = cityArrWithAllCity;
