export default {
    PU_KEY:`
    MIGeMA0GCSqGSIb3DQEBAQUAA4GMADCBiAKBgHDKzzEz/Ej6atPybcUpSg0HNIv6
    ZMv7RVcA1RRSSlppwEazibx75fBG7W0Q5METsN8i9qQCxGPmfrTJCselDOoB4OY3
    jfwN18NOUVWdFzHYxpzIP0gpMXFSzJho1+HUKqqdclmrluE+MfnRwhvHfXM/2oW6
    oUepW6buef16/w/XAgMBAAE=`
}