module.exports = {
  chapters: {
    1: {
      id: 1,
      module_id: 1,
      title: "Historique des réseaux informatiques",
      description:
        "Apprendre l'histoire des réseaux et l'innovation de l'internet",
    },
    2: {
      id: 2,
      module_id: 1,
      title: "Types de réseaux",
      description:
        "Classification des différents types de réseaux informatiques",
    },
    3: {
      id: 3,
      module_id: 1,
      title: "Composants d'un réseau",
      description: "Vue d'ensemble des composants essentiels d'un réseau",
    },
    4: {
      id: 4,
      module_id: 1,
      title: "Topologies de réseau",
      description: "Découverte des différentes structures de réseau",
    },
    5: {
      id: 5,
      module_id: 1,
      title: "Modèles de communication",
      description: "Explication des modèles de communication en réseau",
    },
    6: {
      id: 6,
      module_id: 1,
      title: "Protocoles réseau",
      description:
        "Vue d'ensemble des protocoles utilisés dans les réseaux informatiques",
    },
    7: {
      id: 7,
      module_id: 1,
      title: "Architecture client-serveur",
      description:
        "Explication de l'architecture client-serveur et son fonctionnement",
    },
    8: {
      id: 8,
      module_id: 1,
      title: "Sécurité des réseaux",
      description: "Vue d'ensemble de la sécurité des réseaux informatiques",
    },
    9: {
      id: 9,
      module_id: 1,
      title: "Administration réseau",
      description: "Introduction à l'administration des réseaux informatiques",
    },
    10: {
      id: 10,
      module_id: 1,
      title: "Évolutions récentes dans les réseaux",
      description:
        "Découverte des dernières avancées dans le domaine des réseaux",
    },
    11: {
      id: 11,
      module_id: 2,
      title: "Modèles de communication",
      description: "Explication des modèles de communication en réseau",
    },
    12: {
      id: 12,
      module_id: 2,
      title: "Types de médias de transmission",
      description:
        "Vue d'ensemble des différents médias de transmission utilisés en réseau",
    },
    13: {
      id: 13,
      module_id: 2,
      title: "Protocoles de communication",
      description: "Vue d'ensemble des protocoles de communication en réseau",
    },
    14: {
      id: 14,
      module_id: 2,
      title: "Équipements réseau de base",
      description:
        "Vue d'ensemble des équipements de base utilisés dans les réseaux",
    },
    15: {
      id: 15,
      module_id: 2,
      title: "Adressage IP et masques de sous-réseau",
      description:
        "Explication de l'adressage IP et des masques de sous-réseau",
    },
    16: {
      id: 16,
      module_id: 2,
      title: "Configuration de base d'un routeur",
      description: "Découverte de la configuration de base d'un routeur",
    },
    17: {
      id: 17,
      module_id: 2,
      title: "Configuration de base d'un commutateur",
      description: "Découverte de la configuration de base d'un commutateur",
    },
    18: {
      id: 18,
      module_id: 2,
      title: "Configuration de base d'un point d'accès sans fil",
      description:
        "Découverte de la configuration de base d'un point d'accès sans fil",
    },
    19: {
      id: 19,
      module_id: 2,
      title: "Compréhension des VLAN",
      description:
        "Explication des Virtual LANs (VLANs) et de leur fonctionnement",
    },
    20: {
      id: 20,
      module_id: 2,
      title: "Introduction aux concepts de sécurité réseau",
      description:
        "Introduction aux concepts de sécurité utilisés dans les réseaux informatiques",
    },
    21: {
      id: 21,
      module_id: 11,
      title: "Fonctionnement du routage",
      description: "Explication du fonctionnement du routage dans les réseaux",
    },
    22: {
      id: 22,
      module_id: 11,
      title: "Fonctionnement de la commutation",
      description:
        "Explication du fonctionnement de la commutation dans les réseaux",
    },
    23: {
      id: 23,
      module_id: 11,
      title: "Types de routeurs",
      description:
        "Vue d'ensemble des différents types de routeurs utilisés dans les réseaux",
    },
    24: {
      id: 24,
      module_id: 11,
      title: "Types de commutateurs",
      description:
        "Vue d'ensemble des différents types de commutateurs utilisés dans les réseaux",
    },
    25: {
      id: 25,
      module_id: 11,
      title: "Protocoles de routage",
      description:
        "Vue d'ensemble des protocoles de routage utilisés dans les réseaux",
    },
    26: {
      id: 26,
      module_id: 11,
      title: "Protocoles de commutation",
      description:
        "Vue d'ensemble des protocoles de commutation utilisés dans les réseaux",
    },
    27: {
      id: 27,
      module_id: 11,
      title: "Concepts de routage statique",
      description:
        "Explication des concepts de routage statique et de leur fonctionnement",
    },
    28: {
      id: 28,
      module_id: 11,
      title: "Configuration de base des routeurs",
      description: "Découverte de la configuration de base des routeurs",
    },
    29: {
      id: 29,
      module_id: 11,
      title: "Configuration de base des commutateurs",
      description: "Découverte de la configuration de base des commutateurs",
    },
    30: {
      id: 30,
      module_id: 11,
      title: "Comparaison entre routage et commutation",
      description:
        "Comparaison des concepts de routage et de commutation dans les réseaux",
    },
  },

  courses: {
    1: {
      course_id: 1,
      course_name: "CCNA 1",
      description: "networking fondamentals",
      instructor_id: 1,
    },
    2: {
      course_id: 2,
      course_name: "CCNA 2",
      description: "introductions to LANs",
      instructor_id: 2,
    },
    3: {
      course_id: 3,
      course_name: "CCNA 3",
      description: "Routage and WAN protocols",
      instructor_id: 1,
    },
    4: {
      course_id: 4,
      course_name: "CCNA 4",
      description: "Securite des Resaux",
      instructor_id: 1,
    },
  },

  intructors: {
    1: {
      instructor_id: 1,
      instructor_name: "Hamze",
      speciality: "Networking",
    },
    2: {
      instructor_id: 2,
      instructor_name: "Mohammed",
      speciality: "Coding",
    },
  },

  modules: {
    1: {
      course: 1,
      description: "Concepts fondamentaux des réseaux informatiques.",
      id: 1,
      order: 1,
      title: "Introduction aux Réseaux",
    },
    2: {
      course: 1,
      description: "Principes de base des réseaux de communication.",
      id: 2,
      order: 2,
      title: "Fondamentaux du Réseautage",
    },
    3: {
      course: 1,
      description: "Compréhension du modèle de référence OSI.",
      id: 3,
      order: 3,
      title: "Modèle OSI",
    },
    4: {
      course: 1,
      description: "Fonctionnement du modèle TCP/IP.",
      id: 4,
      order: 4,
      title: "Modèle TCP/IP",
    },
    5: {
      course: 1,
      description: "Technologies et protocoles Ethernet.",
      id: 5,
      order: 5,
      title: "LAN Ethernet",
    },
    6: {
      course: 1,
      description: "Utilisation et configuration des adresses IPv4.",
      id: 6,
      order: 6,
      title: "Adressage IPv4",
    },
    7: {
      course: 1,
      description: "Techniques de subdivision de réseaux IPv4.",
      id: 7,
      order: 7,
      title: "Subdivision des Réseaux IP",
    },
    8: {
      course: 1,
      description: "Technologies et configurations des réseaux sans fil.",
      id: 8,
      order: 8,
      title: "LAN sans fil",
    },
    9: {
      course: 1,
      description: "Principes de base de la sécurité des réseaux.",
      id: 9,
      order: 9,
      title: "Fondamentaux de la Sécurité Réseau",
    },
    10: {
      course: 1,
      description: "Configuration initiale des routeurs Cisco.",
      id: 10,
      order: 10,
      title: "Configuration de Base des Routeurs",
    },
    11: {
      course: 2,
      description: "Principes de base du routage et de la commutation.",
      id: 11,
      order: 1,
      title: "Introduction au Routage et à la Commutation",
    },
    12: {
      course: 2,
      description: "Compréhension des concepts de routage.",
      id: 12,
      order: 2,
      title: "Concepts de Routage",
    },
    13: {
      course: 2,
      description: "Configuration et utilisation du routage statique.",
      id: 13,
      order: 3,
      title: "Routage Statique",
    },
    14: {
      course: 2,
      description: "Utilisation des protocoles de routage dynamique.",
      id: 14,
      order: 4,
      title: "Protocoles de Routage Dynamique",
    },
    15: {
      course: 2,
      description: "Principes fondamentaux de la commutation de paquets.",
      id: 15,
      order: 5,
      title: "Concepts de Commutation",
    },
    16: {
      course: 2,
      description: "Configuration des commutateurs Cisco.",
      id: 16,
      order: 6,
      title: "Configuration des Commutateurs",
    },
    17: {
      course: 2,
      description: "Configuration et gestion des VLANs et tronçons.",
      id: 17,
      order: 7,
      title: "VLANs et Tronçons",
    },
    18: {
      course: 2,
      description: "Mise en place et configuration des ACL.",
      id: 18,
      order: 8,
      title: "Listes de Contrôle d'Accès",
    },
    19: {
      course: 2,
      description: "Fonctionnement et configuration des services DHCP et DNS.",
      id: 19,
      order: 9,
      title: "DHCP et DNS",
    },
    20: {
      course: 2,
      description: "Configuration de la translation d'adresses réseau.",
      id: 20,
      order: 10,
      title: "Traduction d'Adresse Réseau",
    },
    21: {
      course: 3,
      description: "Mise à l'échelle des réseaux d'entreprise.",
      id: 21,
      order: 1,
      title: "Mise à l'Échelle des Réseaux",
    },
    22: {
      course: 3,
      description: "Mise en place de redondance dans les réseaux locaux.",
      id: 22,
      order: 2,
      title: "Redondance LAN",
    },
    23: {
      course: 3,
      description: "Compréhension des concepts de WAN.",
      id: 23,
      order: 3,
      title: "Concepts WAN",
    },
    24: {
      course: 3,
      description: "Exploration des technologies WAN.",
      id: 24,
      order: 4,
      title: "Technologies WAN",
    },
    25: {
      course: 3,
      description: "Examen approfondi des concepts de routage.",
      id: 25,
      order: 5,
      title: "Concepts de Routage",
    },
    26: {
      course: 3,
      description: "Configuration et dépannage d'EIGRP.",
      id: 26,
      order: 6,
      title: "EIGRP",
    },
    27: {
      course: 3,
      description: "Configuration et dépannage d'OSPF.",
      id: 27,
      order: 7,
      title: "OSPF",
    },
    28: {
      course: 3,
      description: "Migration et configuration IPv6.",
      id: 28,
      order: 8,
      title: "IPv6",
    },
    29: {
      course: 3,
      description: "Techniques de dépannage des réseaux.",
      id: 29,
      order: 9,
      title: "Dépannage Réseau",
    },
    30: {
      course: 3,
      description: "Gestion et surveillance des réseaux informatiques.",
      id: 30,
      order: 10,
      title: "Gestion Réseau",
    },
    31: {
      course: 4,
      description: "Interconnexion des réseaux.",
      id: 31,
      order: 1,
      title: "Connexion des Réseaux",
    },
    32: {
      course: 4,
      description: "Exploration des réseaux étendus.",
      id: 32,
      order: 2,
      title: "Réseaux Étendus",
    },
    33: {
      course: 4,
      description: "Concepts et services informatiques en nuage.",
      id: 33,
      order: 3,
      title: "Informatique en Nuage",
    },
    34: {
      course: 4,
      description: "Implémentation de la virtualisation des réseaux.",
      id: 34,
      order: 4,
      title: "Virtualisation Réseau",
    },
    35: {
      course: 4,
      description: "Sécurité des réseaux et des données.",
      id: 35,
      order: 5,
      title: "Sécurité Réseau",
    },
    36: {
      course: 4,
      description: "Automatisation des tâches réseau.",
      id: 36,
      order: 6,
      title: "Automatisation Réseau",
    },
    37: {
      course: 4,
      description: "Utilisation de l'API pour la programmabilité réseau.",
      id: 37,
      order: 7,
      title: "Programmabilité Réseau",
    },
    38: {
      course: 4,
      description: "Introduction aux réseaux définis par logiciel (SDN).",
      id: 38,
      order: 8,
      title: "Réseaux Définis par Logiciel",
    },
    39: {
      course: 4,
      description:
        "Conception et mise en œuvre de réseaux de centre de données.",
      id: 39,
      order: 9,
      title: "Réseautage de Centre de Données",
    },
    40: {
      course: 4,
      description: "Applications et services de l'Internet des Objets (IoT).",
      id: 40,
      order: 10,
      title: "Internet des Objets",
    },
  },

  // tests: {
  //   C00001T00001: {
  //     chapter_id: 1,
  //     options: [
  //       "1969",
  //       "1972",
  //       "1980",
  //       "1990",
  //       "1950",
  //       "1975",
  //       "1985",
  //       "2000",
  //       "1960",
  //       "1970",
  //       "1977",
  //       "1995",
  //       "1965",
  //       "1982",
  //       "2005",
  //       "1979",
  //       "1989",
  //       "1992",
  //       "1967",
  //       "1973",
  //     ],
  //     question:
  //       "Quelle année marque le début de l'ARPANET, l'un des premiers réseaux informatiques?",
  //     test_id: "C00001T00001",
  //     theCorrectAnswer: "1969",
  //   },
  //   C00001T00002: {
  //     chapter_id: 1,
  //     options: [
  //       "États-Unis",
  //       "Royaume-Uni",
  //       "France",
  //       "Allemagne",
  //       "Canada",
  //       "Japon",
  //       "Australie",
  //       "Chine",
  //       "Russie",
  //       "Inde",
  //       "Brésil",
  //       "Italie",
  //       "Espagne",
  //       "Corée du Sud",
  //       "Mexique",
  //       "Suède",
  //       "Pays-Bas",
  //       "Singapour",
  //       "Suisse",
  //       "Norvège",
  //     ],
  //     question: "Dans quel pays a été développé le réseau ARPANET?",
  //     test_id: "C00001T00002",
  //     theCorrectAnswer: "États-Unis",
  //   },
  //   C00001T00003: {
  //     chapter_id: 1,
  //     options: [
  //       "J.C.R. Licklider",
  //       "Vinton Cerf",
  //       "Tim Berners-Lee",
  //       "Larry Roberts",
  //       "Paul Baran",
  //       "Leonard Kleinrock",
  //       "Bob Kahn",
  //       "Ray Tomlinson",
  //       "Steve Crocker",
  //       "John Postel",
  //       "Doug Engelbart",
  //       "David Clark",
  //       "Whitfield Diffie",
  //       "Martin Hellman",
  //       "Jon Postel",
  //       "Paul Mockapetris",
  //       "Steve Crocker",
  //       "Tim Berners Lee",
  //       "Robert Metcalfe",
  //       "Radia Perlman",
  //     ],
  //     question: "Qui est souvent considéré comme le père de l'ARPANET?",
  //     test_id: "C00001T00003",
  //     theCorrectAnswer: "Larry Roberts",
  //   },
  //   C00001T00004: {
  //     chapter_id: 1,
  //     options: [
  //       "Faciliter la communication entre les chercheurs",
  //       "Faciliter les transactions financières",
  //       "Faciliter les échanges commerciaux",
  //       "Faciliter les réunions virtuelles",
  //       "Faciliter la diffusion d'informations gouvernementales",
  //       "Faciliter les transactions bancaires",
  //       "Faciliter l'échange de courriels",
  //       "Faciliter l'accès à l'information",
  //       "Faciliter les achats en ligne",
  //       "Faciliter les recherches universitaires",
  //       "Faciliter la planification de projets",
  //       "Faciliter la gestion des ressources humaines",
  //       "Faciliter la gestion des stocks",
  //       "Faciliter la gestion des entreprises",
  //       "Faciliter les opérations militaires",
  //       "Faciliter les opérations de secours",
  //       "Faciliter les opérations de vente",
  //       "Faciliter les opérations de marketing",
  //       "Faciliter les opérations de logistique",
  //       "Faciliter les opérations de production",
  //     ],
  //     question: "Quel était le principal objectif de la création d'ARPANET?",
  //     test_id: "C00001T00004",
  //     theCorrectAnswer: "Faciliter la communication entre les chercheurs",
  //   },
  //   C00001T00005: {
  //     chapter_id: 1,
  //     options: [
  //       "Département de la Défense des États-Unis",
  //       "NASA",
  //       "IBM",
  //       "Microsoft",
  //       "Apple",
  //       "Google",
  //       "Facebook",
  //       "Amazon",
  //       "Intel",
  //       "HP",
  //       "Cisco",
  //       "Oracle",
  //       "DARPA",
  //       "NSF",
  //       "FBI",
  //       "CIA",
  //       "NSA",
  //       "NIST",
  //       "EPA",
  //       "DOE",
  //     ],
  //     question: "Quelle institution a créé ARPANET?",
  //     test_id: "C00001T00005",
  //     theCorrectAnswer: "Département de la Défense des États-Unis",
  //   },
  //   C00011T00001: {
  //     chapter_id: 11,
  //     options: [
  //       "Modèle OSI",
  //       "Modèle TCP/IP",
  //       "Modèle Internet",
  //       "Modèle Ethernet",
  //       "Modèle ARPANET",
  //       "Modèle UDP",
  //       "Modèle HTTP",
  //       "Modèle FTP",
  //       "Modèle SMTP",
  //       "Modèle SNMP",
  //       "Modèle ICMP",
  //       "Modèle DNS",
  //       "Modèle POP3",
  //       "Modèle IMAP",
  //       "Modèle VoIP",
  //       "Modèle SSL/TLS",
  //       "Modèle BGP",
  //       "Modèle SSH",
  //       "Modèle VLAN",
  //       "Modèle MPLS",
  //     ],
  //     question:
  //       "Quel est le modèle de communication largement utilisé pour les réseaux informatiques?",
  //     test_id: "C00011T00001",
  //     theCorrectAnswer: "Modèle OSI",
  //   },
  //   C00011T00002: {
  //     chapter_id: 11,
  //     options: [
  //       "Encapsulation des données",
  //       "Contrôle de flux",
  //       "Conversion de signaux",
  //       "Accès au réseau",
  //       "Conversion de fréquences",
  //       "Transmission de paquets",
  //       "Modulation de données",
  //       "Décapsulation de données",
  //       "Transmission de trames",
  //       "Analyse de paquets",
  //       "Gestion de la congestion",
  //       "Routage des paquets",
  //       "Filtrage des données",
  //       "Redirection des paquets",
  //       "Analyse du trafic",
  //       "Authentification des utilisateurs",
  //       "Sécurisation des données",
  //       "Compression des données",
  //       "Chiffrement des données",
  //       "Déchiffrement des données",
  //     ],
  //     question:
  //       "Quelle est la fonction principale de la couche physique dans le modèle OSI?",
  //     test_id: "C00011T00002",
  //     theCorrectAnswer: "Conversion de signaux",
  //   },
  //   C00011T00003: {
  //     chapter_id: 11,
  //     options: [
  //       "Couche Transport",
  //       "Couche Application",
  //       "Couche Réseau",
  //       "Couche Liaison de données",
  //       "Couche Session",
  //       "Couche Physique",
  //       "Couche Présentation",
  //       "Couche Sous-réseau",
  //       "Couche Accès au réseau",
  //       "Couche Contrôle de flux",
  //       "Couche Fiabilité de la communication",
  //       "Couche Routage",
  //       "Couche Encapsulation",
  //       "Couche Détection d'erreurs",
  //       "Couche Multiplexage",
  //       "Couche Désencapsulation",
  //       "Couche Reroutage",
  //       "Couche Partitionnement",
  //       "Couche Cryptage",
  //       "Couche Authentification",
  //     ],
  //     question:
  //       "Quelle couche du modèle OSI est responsable du transfert de données de bout en bout?",
  //     test_id: "C00011T00003",
  //     theCorrectAnswer: "Couche Transport",
  //   },
  //   C00011T00004: {
  //     chapter_id: 11,
  //     options: [
  //       "IP",
  //       "HTTP",
  //       "TCP",
  //       "DNS",
  //       "FTP",
  //       "SMTP",
  //       "UDP",
  //       "IMAP",
  //       "POP3",
  //       "ARP",
  //       "ICMP",
  //       "SNMP",
  //       "SSH",
  //       "Telnet",
  //       "NTP",
  //       "SMTPS",
  //       "SIP",
  //       "TLS",
  //       "SSL",
  //       "RTP",
  //     ],
  //     question:
  //       "Quel est le principal protocole de la couche réseau dans le modèle TCP/IP?",
  //     test_id: "C00011T00004",
  //     theCorrectAnswer: "IP",
  //   },
  //   C00011T00005: {
  //     chapter_id: 11,
  //     options: [
  //       "Assurer la fiabilité de la communication",
  //       "Gérer l'adressage logique",
  //       "Assurer la connectivité physique",
  //       "Convertir les données en signaux",
  //       "Contrôler l'accès au réseau",
  //       "Identifier les hôtes sur le réseau",
  //       "Résoudre les noms de domaine",
  //       "Filtrer les paquets de données",
  //       "Gérer la congestion du réseau",
  //       "Crypter les données transitant sur le réseau",
  //       "Authentifier les utilisateurs du réseau",
  //       "Fournir un service de messagerie électronique",
  //       "Assurer la transmission sécurisée des données",
  //       "Faciliter la communication entre les couches OSI",
  //       "Assurer la synchronisation des données",
  //       "Gérer les connexions entre les hôtes",
  //       "Vérifier l'intégrité des données",
  //       "Identifier les erreurs de transmission",
  //       "Faciliter le partage de fichiers sur le réseau",
  //       "Assurer la redondance des données",
  //     ],
  //     question:
  //       "Quelle est la principale fonction de la couche Transport dans le modèle TCP/IP?",
  //     test_id: "C00011T00005",
  //     theCorrectAnswer: "Assurer la fiabilité de la communication",
  //   },
  // },

  utilisateurs: {
    NHuXe29M6l916z15w0rc: {
      email: "med@mail.com",
      name: "med",
      password: "0000",
      profile: "user",
    },
    UsyK0Z0TVhZO0KUDfMms: {
      email: "0",
      name: "TestUser",
      password: "0",
      profile: "user",
    },
    ouPRHjQXdM94c3l2yb9i: {
      email: "0@m.com",
      name: "Test",
      password: "0",
      profile: "user",
    },
    yM9kKKg9oaO3MKdLrv6J: {
      email: "hamza@mail.com",
      name: "Hamza",
      password: "1234",
      profile: "admin",
    },
  },
  tests: {
    1: [
      {
        id: 1,
        question: "When was the Internet invented?",
        quiz: 1,
        correctAnswer: 2,
        answers: ["1950s", "1960s", "1970s", "1980s", "1990s"],
      },
      {
        id: 2,
        question: "What is the main purpose of computer networks?",
        quiz: 1,
        correctAnswer: 0,
        answers: [
          "Sharing resources and information",
          "Playing video games",
          "Sending emails",
          "Storing files",
        ],
      },
      {
        id: 3,
        question: "Which of the following is a type of computer network?",
        quiz: 1,
        correctAnswer: 3,
        answers: ["LAN", "WAN", "MAN", "All of the above"],
      },
      {
        id: 4,
        question: "What does ARPANET stand for ?",
        quiz: 1,
        correctAnswer: 0,
        answers: [
          "Advanced Research Projects Agency Network",
          "Advanced Routing Protocol Network",
          "Association of Research Projects and Network",
          "Automated Response and Processing Network",
        ],
      },
      {
        id: 5,
        question:
          "Quel était le problème principal avec les réseaux informatiques primitifs ?",
        quiz: 2,
        correctAnswer: 2,
        answers: [
          "La lenteur des connexions",
          "L'absence de disques durs",
          "**Les protocoles et standards propriétaires**",
          "Les pannes fréquentes des ordinateurs centraux",
        ],
      },
      {
        id: 6,
        question:
          "Quels étaient les fabricants pionniers dans le domaine des réseaux informatiques primitifs ?",
        quiz: 2,
        correctAnswer: 0,
        answers: [
          "**Digital et IBM**",
          "Macroplata et DECnet",
          "Macroplata et Pliosaures",
          "IBM et Pliosaures",
        ],
      },
      {
        id: 7,
        question:
          "Quelle était la conséquence de l'utilisation de protocoles et de standards propriétaires par chaque fabricant ?",
        quiz: 2,
        correctAnswer: 0,
        answers: [
          "**L'impossibilité de faire communiquer des machines de fabricants différents**",
          "Une augmentation de la vitesse des connexions",
          "Une amélioration de la sécurité des réseaux",
          "Une diminution des coûts de maintenance des réseaux",
        ],
      },
      {
        id: 8,
        question:
          "**Question hors sujet** Quelle transformation ont subie les pattes des Pliosaures pour devenir des palettes natatoires ?",
        quiz: 2,
        correctAnswer: 0,
        answers: [
          "**L'agrandissement du nombre de phalanges**",
          "L'allongement du cou",
          "Le doublement de la taille du crâne",
          "L'ajout de disques durs aux terminaux",
        ],
      },

      {
        id: 9,
        question:
          "Quel était le problème principal avec les réseaux informatiques primitifs ?",
        quiz: 2,
        correctAnswer: 2,
        answers: [
          "La lenteur des connexions",
          "L'absence de disques durs",
          "**Les protocoles et standards propriétaires**",
          "Les pannes fréquentes des ordinateurs centraux",
        ],
      },
      {
        id: 10,
        question:
          "Quels étaient les fabricants pionniers dans le domaine des réseaux informatiques primitifs ?",
        quiz: 2,
        correctAnswer: 0,
        answers: [
          "**Digital et IBM**",
          "Macroplata et DECnet",
          "Macroplata et Pliosaures",
          "IBM et Pliosaures",
        ],
      },
      {
        id: 11,
        question:
          "Quelle était la conséquence de l'utilisation de protocoles et de standards propriétaires par chaque fabricant ?",
        quiz: 1,
        correctAnswer: 0,
        answers: [
          "**L'impossibilité de faire communiquer des machines de fabricants différents**",
          "Une augmentation de la vitesse des connexions",
          "Une amélioration de la sécurité des réseaux",
          "Une diminution des coûts de maintenance des réseaux",
        ],
      },
      {
        id: 12,
        question:
          "**Question hors sujet** Quelle transformation ont subie les pattes des Pliosaures pour devenir des palettes natatoires ?",
        quiz: 2,
        correctAnswer: 0,
        answers: [
          "**L'agrandissement du nombre de phalanges**",
          "L'allongement du cou",
          "Le doublement de la taille du crâne",
          "L'ajout de disques durs aux terminaux",
        ],
      },
    ],
    2: [
      {
        id: 1,
        question: "What is the difference between LAN and WAN?",
        correctAnswer: 1,
        answers: [
          "LAN is faster than WAN",
          "LAN is a local network while WAN is a wide area network",
          "LAN uses wireless technology while WAN uses wired technology",
          "LAN is more secure than WAN",
        ],
      },
      {
        id: 2,
        question: "What is a network topology?",
        correctAnswer: 0,
        answers: [
          "The physical or logical arrangement of computers in a network",
          "The speed of data transmission in a network",
          "The number of computers connected to a network",
          "The distance between computers in a network",
        ],
      },
      {
        id: 3,
        question: "Which of the following is a type of network topology?",
        correctAnswer: 2,
        answers: [
          "Single hop topology",
          "Point-to-point topology",
          "Star topology",
          "All of the above",
        ],
      },
    ],
    3: [
      {
        id: 1,
        question: "What is a network protocol?",
        correctAnswer: 3,
        answers: [
          "A software application that connects to the internet",
          "A type of network cable",
          "A device used to connect computers in a network",
          "A set of rules for communication between devices in a network",
        ],
      },
      {
        id: 2,
        question: "Which protocol is used for email communication?",
        correctAnswer: 1,
        answers: ["HTTP", "SMTP", "FTP", "TCP"],
      },
      {
        id: 3,
        question: "What is the OSI model?",
        correctAnswer: 0,
        answers: [
          "A conceptual model that characterizes and standardizes the communication functions of a telecommunication or computing system without regard to its underlying internal structure and technology",
          "An internet service provider",
          "A type of network cable",
          "A protocol used for web browsing",
        ],
      },
    ],
    4: [
      {
        id: 1,
        question: "What is a router?",
        correctAnswer: 2,
        answers: [
          "A device used to connect computers in a network",
          "A type of network cable",
          "A device that forwards data packets between computer networks",
          "A software application that connects to the internet",
        ],
      },
      {
        id: 2,
        question: "What is a switch?",
        correctAnswer: 0,
        answers: [
          "A device used to connect computers in a network",
          "A type of network cable",
          "A device that forwards data packets between computer networks",
          "A software application that connects to the internet",
        ],
      },
      {
        id: 3,
        question: "What is a modem?",
        correctAnswer: 3,
        answers: [
          "A device used to connect computers in a network",
          "A type of network cable",
          "A device that forwards data packets between computer networks",
          "A device that modulates and demodulates signals for transmission",
        ],
      },
    ],
    5: [
      {
        id: 1,
        question: "What is the client-server model?",
        correctAnswer: 0,
        answers: [
          "A network architecture in which each computer or process on the network is either a client or a server",
          "A type of network cable",
          "A device used to connect computers in a network",
          "A protocol used for web browsing",
        ],
      },
      {
        id: 2,
        question: "What is a firewall?",
        correctAnswer: 1,
        answers: [
          "A device used to connect computers in a network",
          "A security system that monitors and controls incoming and outgoing network traffic",
          "A protocol used for email communication",
          "A software application that connects to the internet",
        ],
      },
      {
        id: 3,
        question: "What is VPN?",
        correctAnswer: 2,
        answers: [
          "A type of network cable",
          "A software application that connects to the internet",
          "A virtual private network that extends a private network across a public network",
          "A device that forwards data packets between computer networks",
        ],
      },
    ],
    6: [
      {
        id: 1,
        question: "What is TCP/IP?",
        correctAnswer: 2,
        answers: [
          "A type of network cable",
          "A protocol used for email communication",
          "A set of networking protocols used for the Internet",
          "An internet service provider",
        ],
      },
      {
        id: 2,
        question: "What is DNS?",
        correctAnswer: 0,
        answers: [
          "A hierarchical and decentralized naming system for computers, services, or other resources connected to the Internet or a private network",
          "A protocol used for web browsing",
          "A device used to connect computers in a network",
          "A security system that monitors and controls incoming and outgoing network traffic",
        ],
      },
      {
        id: 3,
        question: "What is DHCP?",
        correctAnswer: 1,
        answers: [
          "A protocol used for email communication",
          "A network management protocol used on IP networks",
          "A device that forwards data packets between computer networks",
          "A software application that connects to the internet",
        ],
      },
    ],
    7: [
      {
        id: 1,
        question: "What is a client in client-server architecture?",
        correctAnswer: 0,
        answers: [
          "A computer or process that requests a service from a server",
          "A security system that monitors and controls incoming and outgoing network traffic",
          "A protocol used for email communication",
          "A device used to connect computers in a network",
        ],
      },
      {
        id: 2,
        question: "What is a server in client-server architecture?",
        correctAnswer: 1,
        answers: [
          "A computer or process that provides a service to clients",
          "A device that forwards data packets between computer networks",
          "A software application that connects to the internet",
          "A type of network cable",
        ],
      },
      {
        id: 3,
        question: "What is HTTP?",
        correctAnswer: 2,
        answers: [
          "A type of network cable",
          "A security system that monitors and controls incoming and outgoing network traffic",
          "Hypertext Transfer Protocol, a protocol used for transmitting hypermedia documents",
          "A device used to connect computers in a network",
        ],
      },
    ],
    8: [
      {
        id: 1,
        question: "What is network security?",
        correctAnswer: 2,
        answers: [
          "A type of network cable",
          "A protocol used for email communication",
          "The practice of securing a computer network infrastructure",
          "A hierarchical and decentralized naming system for computers, services, or other resources connected to the Internet or a private network",
        ],
      },
      {
        id: 2,
        question: "What is a firewall?",
        correctAnswer: 0,
        answers: [
          "A network security system that monitors and controls incoming and outgoing network traffic",
          "A protocol used for web browsing",
          "A device used to connect computers in a network",
          "A security system that monitors and controls incoming and outgoing network traffic",
        ],
      },
      {
        id: 3,
        question: "What is encryption?",
        correctAnswer: 3,
        answers: [
          "A device used to connect computers in a network",
          "A type of network cable",
          "A protocol used for email communication",
          "The process of converting information or data into a code",
        ],
      },
    ],
    9: [
      {
        id: 1,
        question: "What is network administration?",
        correctAnswer: 0,
        answers: [
          "The process of managing and maintaining a computer network infrastructure",
          "A protocol used for email communication",
          "A type of network cable",
          "A device used to connect computers in a network",
        ],
      },
      {
        id: 2,
        question: "What is a network administrator?",
        correctAnswer: 1,
        answers: [
          "A person responsible for managing and maintaining a computer network infrastructure",
          "A network security system that monitors and controls incoming and outgoing network traffic",
          "A device that forwards data packets between computer networks",
          "A security system that monitors and controls incoming and outgoing network traffic",
        ],
      },
      {
        id: 3,
        question: "What is SNMP?",
        correctAnswer: 2,
        answers: [
          "A type of network cable",
          "A software application that connects to the internet",
          "Simple Network Management Protocol, a protocol used for network management",
          "A virtual private network that extends a private network across a public network",
        ],
      },
    ],
    10: [
      {
        id: 1,
        question: "What are some recent advances in networking?",
        correctAnswer: 3,
        answers: [
          "The invention of the World Wide Web",
          "The introduction of smartphones",
          "The development of 5G technology",
          "All of the above",
        ],
      },
      {
        id: 2,
        question: "What is cloud computing?",
        correctAnswer: 0,
        answers: [
          "The practice of using a network of remote servers hosted on the Internet to store, manage, and process data",
          "A protocol used for email communication",
          "A device used to connect computers in a network",
          "A security system that monitors and controls incoming and outgoing network traffic",
        ],
      },
      {
        id: 3,
        question: "What is IoT?",
        correctAnswer: 2,
        answers: [
          "A type of network cable",
          "A software application that connects to the internet",
          "The Internet of Things, the interconnection via the Internet of computing devices embedded in everyday objects, enabling them to send and receive data",
          "A virtual private network that extends a private network across a public network",
        ],
      },
    ],
  },
};
